title: "【Amplify Studio×LIFF×Figma】ローコードで電子チケットアプリを作るハンズオン"
summary: "Figmaでローコード開発しよう！"
topics: []
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - introduction
  - setup-liff
  - setup-cloud9
  - setup-amplify
  - develop-amplifystudio
  - develop-react
